### PR TITLE
refactor: use v2 CSDK, v2.2 libmraa

### PR DESCRIPTION
**Pull request by iain-anderson**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-grove-c/blob/master/.github/CONTRIBUTING.md

## What is the current behavior?

DS uses the 1.3 SDK which is not compatible with EdgeX v2
Also uses an old version of the mraa driver library which needs to be patched to support R-Pi 3

## What is the new behavior?
DS ported for EdgeX v2/Ireland
Uses libmraa v2.2 which supports R-Pi up to v4 directly

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

## New Imports

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by iain-anderson** [comment]
recheck

**Comment by iain-anderson** [comment]
recheck

**Comment by iain-anderson** [comment]
recheck

**Review by BinduRao2018 — APPROVED** [review]
LGTM

**Pull request merged**
