### PR TITLE
Add snap packaging of device-grove-c

### LINKED ISSUE #11: Snap packaging for device-grove
Similar to `device-mqtt` and `device-modbus`, we should create a snap package for this repo, probably named `edgex-device-grove`. This would need the project to register the snap name and create a track for the `edinburgh` release.

I produced a snap package for similar device service that uses the C SDK for @mhall119 at https://github.com/mhall119/edgex-device-rpi/ so that snapcraft.yaml could probably be easily adapted for this repo. Unfortunately I would need help testing it as I don't have access to any of the grove sensors or devices.

In addition to this, we would additionally want an `edinburgh` track for the snap that the LF folks would need to request.

To do this, we should do the following things in order:

1. Open a PR here with the snapcraft.yaml added to the repo (but don't merge)
2. Deploy jenkins snap verify job for this repo to the jenkins sandbox
3. Open PR to ci-management with the snap verify and stage jobs, referencing the sandbox jobs for testing, etc.
4. Merge the ci-management PR
5. Close the original PR from 1, and re-open to trigger the new verify jobs
6. Merge the PR here
7. Should probably also update the README here to mention the snap

This issue can be assigned to me

### PR DESCRIPTION
**Pull request by anonymouse64**
This adds a snap of (currently Fuji since it's the master branch) device-grove-c.

This PR is currently a draft to setup the branches so we can test the jobs in the sandbox and get the jobs setup in Jenkins on ci-mangement

Fixes: #11 

ci-management PR here has been merged: https://github.com/edgexfoundry/ci-management/pull/433

This PR is now ready for review.

To test this snap, on an Raspberry Pi 3B+ that is running an arm64 image, such as what you get by following the setup instructions for the ubuntu server 18.04.2 found [here](https://wiki.edgexfoundry.org/display/FA/Running+on+a+RaspberryPi), do the following to build and install the snap:

1. Install `snapcraft` and `lxd` with `snap install snapcraft --classic` and by following the instructions here for [lxd](https://linuxcontainers.org/lxd/getting-started-cli/#ubuntu)
2. Checkout this branch using git
3. Build the snap by going to the root directory of this project and running `snapcraft --use-lxd`.
4. Install the `edgexfoundry` snap from the `edinburgh/beta` channel with `snap install edgexfoundry --channel=edinburgh/beta` - note you should do this first so that the EdgeX services are available when device-grove starts up after being install in the next step
5. The build from step 3 should have produced a .snap file named `edgex-device-grove*.snap`, install this snap with `snap install --dangerous edgex-device-grove*.snap`

Assuming all of the above works, the snap is installed and the things to check are:

[ ] the daemon in the snap starts up, check with `snap services edgex-device-grove` all services listed there should be `active` and `enabled`
[ ] the daemon loads the default Grove_Device.yaml file from `/var/snap/edgex-device-grove/current/config/device-grove/profiles/Grove_Device.yaml` into core-metadata, etc.
[ ] the configuration.toml file doesn't contain any references to the revision, i.e. all paths under `/var/snap/edgex-device-grove/` start with `current` as in `/var/snap/edgex-device-grove/current/...` and _not_ `/var/snap/edgex-device-grove/x1/...`

Additionally, if you have access to the grove sensors, try loading some of the device profiles from `/snap/edgex-device-grove/current/config/edgex-device-grove/res/example-profiles` and make sure that curl commands produce correct output. I don't have access to any grove sensors so unfortunately I was unable to do this, but since it's basically the same code as the docker container it should work the same I think.

You can see logs from the daemon with `snap logs -f -n=all edgex-device-grove` or `journalctl -ef -u snap.edgex-device-grove.*`

### CODE REVIEW

**Review by jamesrgregg — DISMISSED** [review]
LGTM

**Comment by anonymouse64** [comment]
Triggered the snap verify jobs and updated the PR description. This PR is now ready for review/merging

**Review by SteveOss — COMMENTED** [review]
In the CMake file think a simpler fix is just to add "-pthread" to CMAKE_C_FLAGS.

Also although nothing to do with PR. IMHO better setting C version with "set (CMAKE_C_STANDARD 99)" as opposed to the gcc specific "std=c99"

**Comment by anonymouse64** [comment]
@SteveOss okay, updated both things

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
