### PR TITLE
DG-15: Updates to device-grove service for Edinburgh release

### PR DESCRIPTION
**Pull request by BinduRao2018**
Signed-off-by: br <bindu@iotechsys.com>

### CODE REVIEW

**Comment by BinduRao2018** [comment]
recheck

**Comment by jamesrgregg** [comment]
recheck

**Comment by BinduRao2018** [comment]
recheck

**Comment by BinduRao2018** [comment]
recheck

**Comment by BinduRao2018** [comment]
@SteveOss, could you please review ?

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
