### PR TITLE
Fixed link typo in README

### PR DESCRIPTION
**Pull request by lranjbar**
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

### CODE REVIEW

**Review by SteveOss — APPROVED** [review]
LGTM. Need to investigate why pre-commit check is failing?

**Comment by jamesrgregg** [comment]
recheck

**Comment by jamesrgregg** [comment]
@MightyNerdEric this seems to fail in the middle and it seems related to Nexus.  Could you please take a look.  This was passed all verify checks in Sandbox.

**Comment by eb-oss** [comment]
recheck

**Comment by eb-oss** [comment]
recheck

**Pull request merged**
